import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import ts from 'typescript';
const source=fs.readFileSync('app/api/ai/route.ts','utf8');
const code=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText;
let signedIn=true, calls=0, upstreamStatus=200, upstreamBody={data:[{id:'test-model'}]},lastRequest;
const sandbox={exports:{},require:()=>({getChatGPTUser:async()=>signedIn?{userId:'test-user'}:null}),Response,Request,URL,AbortSignal,fetch:async(url,options)=>{calls++;lastRequest={url,options};return Response.json(upstreamBody,{status:upstreamStatus})}};
vm.runInNewContext(code,sandbox);
const send=(body,origin='https://notes.test')=>sandbox.exports.POST(new Request('https://notes.test/api/ai',{method:'POST',headers:{origin,'Content-Type':'application/json'},body:JSON.stringify(body)}));
const base={provider:'OpenAI',key:'test-only-placeholder',model:'test-model',prompt:'Summarize',context:'A short note.',maxTokens:1500};
signedIn=false;assert.equal((await send(base)).status,401);signedIn=true;
assert.equal((await send(base,'https://elsewhere.test')).status,403);
assert.equal((await send({...base,provider:'invalid'})).status,400);assert.equal(calls,0);
let response=await send({...base,action:'test'});assert.equal(response.status,200);assert.deepEqual((await response.json()).models,['test-model']);assert.equal(lastRequest.options.method,'GET');
upstreamBody={choices:[{message:{content:'Summary'},finish_reason:'stop'}],usage:{total_tokens:20}};
response=await send(base);assert.equal((await response.json()).text,'Summary');assert.equal(lastRequest.url,'https://api.openai.com/v1/chat/completions');assert.equal(JSON.parse(lastRequest.options.body).max_completion_tokens,1500);
await send({...base,provider:'Groq',maxTokens:99999});assert.equal(JSON.parse(lastRequest.options.body).max_tokens,4096);
await send({...base,provider:'OpenRouter'});assert.equal(lastRequest.url,'https://openrouter.ai/api/v1/chat/completions');
upstreamStatus=401;upstreamBody={error:{message:'secret upstream error'}};response=await send(base);const error=await response.json();assert.ok(error.error.includes('rejected'));assert.ok(!JSON.stringify(error).includes('secret upstream'));
upstreamStatus=429;assert.ok((await (await send(base)).json()).error.includes('quota'));
upstreamStatus=200;upstreamBody={choices:[{message:{content:''}}]};assert.equal((await send(base)).status,502);
assert.equal((await send({...base,context:'x'.repeat(170000)})).status,413);
console.log('PASS: authentication, origin validation, provider allowlist, key test, generation, token limits, all providers, safe errors, empty output, oversized input. No live API calls.');
